/*
 * Autogenerated by ConfigTool (1.0.0)
 */

#pragma once

#include <string>
#include "Config.h"

struct DemoConfigSectionBusi {
  Config::Value Age;
  Config::Value Name;
  void Load(Config::Ini& ini) {
    Age.SetData(ini.GetStrValue("Busi", "Age", ""));
    Name.SetData(ini.GetStrValue("Busi", "Name", ""));
  }
};

struct DemoConfigSectionserver {
  Config::Value MaxLoop;
  Config::Value host;
  Config::Value len;
  void Load(Config::Ini& ini) {
    MaxLoop.SetData(ini.GetStrValue("server", "MaxLoop", ""));
    host.SetData(ini.GetStrValue("server", "host", ""));
    len.SetData(ini.GetStrValue("server", "len", ""));
  }
};

class DemoConfig {
public:
  bool Load(std::string fileName) {
    Config::Ini ini;
    if (!ini.Load(fileName)) {
      return false;
    }
    Busi.Load(ini);
    server.Load(ini);
    return true;
  }

public:
  DemoConfigSectionBusi Busi;
  DemoConfigSectionserver server;
};
